name: socket_connector
description: Package allows you to join two TCP clients or two servers this package includes all the tools you need to connet and optionally print the traffic.

version: 1.0.11
repository: https://github.com/cconstab/socket_connector

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  chalkdart: ^2.0.9
