name: socket_connector
description: Package allows you to join two TCP clients or two servers this package includes all the tools you need to connect and optionally print the traffic.

version: 2.0.0
repository: https://github.com/cconstab/socket_connector

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  chalkdart: ^2.2.1
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
