name: socket_connector
description: Package for joining sockets together to create socket relays.

version: 2.2.0
repository: https://github.com/cconstab/socket_connector

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  chalkdart: ^2.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
